config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get '/home', to: 'home#index'
  root 'home#index'

  # lets add some routes for our Users
  #resources :users, :only => [:index, :show, :destroy]
  #resources :users, except: [:new]

  resources :users, except: [:new] do
    member do
      delete :delete_avatar
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one_attached :avatar

  def is_admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :authorize_user!, only: [:destroy]
  
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @user = User.find(params[:id])
      respond_to do |format|
        if @user.destroy
          redirect_to users_url, notice: 'User was successfully destroyed.'
        else
          redirect_to users_url, alert: 'Failed to destroy user.'
        end
      end
    end

    def delete_avatar
      @user = User.find(params[:id])
      @user.avatar.purge
      redirect_to @user, notice: 'Avatar was successfully deleted.'
    end
  
    private
      def set_user
        @user = User.find(params[:id])
      end

      def authorize_user!
        unless current_user.is_admin? || current_user == @user
          redirect_to root_path, alert: "You are not authorized to perform this action."
        end
      end
  
      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :is_admin, :avatar)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_navbar.html.erb
    <!-- top nav -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="/images/231webdev-logo-2020-small.png" alt="Bootstrap" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active text-light" aria-current="page" href="/users">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
           <% if user_signed_in? %>
              <div class="nav-item">
                <div class="d-flex">
                  <div class="me-3 text-light" style="margin-top:6px;"><%= current_user.email %></div>
                  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
                </div>
              </div>
            <% else %>
              <div class="nav-item">
                <%= button_to "Sign in", new_user_session_path, class: "btn btn-outline-light" %>
              </div>
            <% end %>
        </div>
      </div>
    </nav>
    <!-- END top nav -->

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<% if user_signed_in? %> 
 <div> Welcome <b><%= current_user.email %></b></div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
<% else %>
  <%= button_to "Sign in", new_user_session_path, class: "btn btn-outline-primary" %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test Devise Users</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

  <%= render "common/navbar" %>


    <div class="container" style="margin-top:10px;">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %> alert-primary alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, html: { "data-turbo" => "false" }) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :first_name, class: 'form-label' %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :last_name, class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>

<% if current_user && current_user.is_admin? %>
  <div class="mb-3">
    <%= form.label :is_admin, class: 'form-label' %>
    <%= form.check_box :is_admin, class: 'form-check-input' %>
  </div>
<% end %>

<!--
  <div class="mb-3">
    <%= form.label :password, class: 'form-label' %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation, 'Confirm Password', class: 'form-label' %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>
-->

  <div class="mb-3">
    <%= form.label :avatar, class: 'form-label' %>
    <%= form.file_field :avatar, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if (current_user && current_user.is_admin?) || (current_user && current_user.id == @user.id ) %>

<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to "Cancel", user_path(@user), class: "btn btn-secondary" %>


<% else %>
  <h2>You are not authorized to be here. </h2>
  <a href="/" class="btn btn-primary">Return Home</a>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Is Admin</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.is_admin ? 'Yes' : 'No' %></td>
        <td>
          <%= link_to "Show", user_path(user), class: "btn btn-sm btn-outline-primary me-1" %>
        <% if (current_user && current_user.is_admin? || current_user && user.id == current_user.id) %>
          <%= link_to "Edit", edit_user_path(user), class: "btn btn-sm btn-outline-secondary me-1" %>
          <%= link_to "Delete", 
                      user_path(user), 
                      method: :delete, 
                      "data-turbo-method": "delete",
                      "data-turbo-confirm": { confirm: "Are you sure?", turbo: false }, 
                      class: "btn btn-sm btn-outline-danger" %>
        <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: 'btn btn-secondary' %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<table class="table table-striped">
  <tbody>
    <tr>
      <th>First Name</th>
      <td><%= @user.first_name %></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= @user.last_name %></td>
    </tr>
    <tr>
      <th>Is Admin</th>
      <td><%= @user.is_admin ? 'Yes' : 'No' %></td>
    </tr>
  </tbody>
</table>

<div class="container text-center">
  <div class="row">
    <div class="col">
      
    </div>
    <div class="col">
      <%#= image_tag(@user.avatar, style: 'max-width: 300px;') if @user.avatar.attached? %>
      <br>
      <% if @user.avatar.attached? %>
        <%= image_tag(@user.avatar, class: 'user-avatar', style: 'max-width: 300px;') %>
        <%#= link_to 'Delete Avatar', 
            delete_avatar_user_path(@user), 
            method: :delete,
            "data-turbo-action": "replace",
            "data-turbo-confirm": "Are you sure?", 
            class: 'btn btn-danger' %>

        <%= button_to 'Delete Avatar', 
          delete_avatar_user_path(@user), 
          method: :delete, 
          form: { 'data-turbo-action': 'replace' }, 
          "data-turbo-confirm": "Are you sure?", 
          class: 'btn btn-danger' %>


      <% end %>
    </div>
    <div class="col">
      
    </div>
  </div>
</div>


<% if (current_user && current_user.is_admin? || current_user && @user.id == current_user.id) %>
<%= link_to "Edit", edit_user_path(@user), class: "btn btn-primary" %>
<% end %>
<%= link_to "Back", users_path, class: "btn btn-secondary" %>